#!/bin/bash

echo "🔐 YouTube API Setup Guide"
echo "=========================="
echo ""
echo "To enable automated uploads, you need to:"
echo ""
echo "1. Go to: https://console.cloud.google.com"
echo "2. Create a new project or select existing"
echo "3. Enable YouTube Data API v3"
echo "4. Create OAuth 2.0 credentials"
echo "5. Download credentials and set environment variables:"
echo ""
echo "export YOUTUBE_CLIENT_ID='your-client-id'"
echo "export YOUTUBE_CLIENT_SECRET='your-client-secret'"
echo ""
echo "Then run:"
echo "node upload-to-youtube.js output/youtube-ready.mp4 output/youtube-ready_youtube.json"
echo ""
echo "OR just drag the video file to YouTube Studio manually!"
echo "The video is ready at: output/youtube-ready.mp4"